{{- if .Values.web.enabled -}}
{{- $component := "web" -}}
{{- $ctx := dict "root" . "component" $component -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "midwater.componentName" $ctx }}
  labels:
    {{- include "midwater.labels" . | nindent 4 }}
    {{- include "midwater.selectorLabels" $ctx | nindent 4 }}
spec:
  {{- if not .Values.web.autoscaling.hpa.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "midwater.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels: {{- include "midwater.selectorLabels" $ctx | nindent 8 }}
    spec:
      serviceAccountName: {{ include "midwater.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "midwater.image" (dict "root" . "img" .Values.web.image) }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - { name: http, containerPort: {{ .Values.web.service.targetPort }}, protocol: TCP }
          env:
            - { name: APP_ENV, value: {{ .Values.global.env | quote }} }
            - { name: APP_DOMAIN, value: {{ .Values.global.domain | quote }} }
            {{- with .Values.web.env }}{{- toYaml . | nindent 12 }}{{- end }}
          {{- if or .Values.web.envFromSecrets .Values.web.envFromConfigMaps }}
          envFrom:
            {{- range .Values.web.envFromSecrets }}
            - secretRef: { name: {{ . }} }
            {{- end }}
            {{- range .Values.web.envFromConfigMaps }}
            - configMapRef: { name: {{ . }} }
            {{- end }}
          {{- end }}
          livenessProbe: {{- toYaml .Values.web.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.web.readinessProbe | nindent 12 }}
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          volumeMounts:
            - { name: tmp,        mountPath: /tmp }
            - { name: nginx-run,  mountPath: /var/run }
            - { name: nginx-cache, mountPath: /var/cache/nginx }
      volumes:
        - { name: tmp,         emptyDir: {} }
        - { name: nginx-run,   emptyDir: {} }
        - { name: nginx-cache, emptyDir: {} }
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
