apiVersion: v1
kind: Service
metadata:
  name: simplify-worker
  namespace: midwater
  labels:
    app.kubernetes.io/name: simplify-worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: simplify-worker
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: simplify-worker-pdb
  namespace: midwater
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simplify-worker
