/**
 * Midwater Supplier Catalog — Built-in supplier data
 */

import type { Supplier } from './types';

export const SUPPLIERS: Supplier[] = [
  {
    id: 'precision-works',
    name: 'Precision Works LLC',
    materials: ['al-6061', 'al-7075', 'ss-304', 'ss-316', 'ti-6al4v'],
    processes: ['cnc-milling', 'cnc-turning', 'edm'],
    maxComplexity: 0.85,
    advancedSurfaces: ['freeform', 'toroidal', 'spherical'],
    leadTimeDays: 10,
    qualityRating: 0.95,
    region: 'US-West',
    minOrderUsd: 200,
    pricingMultiplier: 1.15,
    materialPricing: { 'ti-6al4v': 1.25, 'inconel-718': 1.4 },
    processPricing: { 'edm': 1.2 },
    volumeDiscounts: [
      { minQuantity: 10, discountPct: 5 },
      { minQuantity: 50, discountPct: 12 },
      { minQuantity: 200, discountPct: 18 },
    ],
    certifications: ['ISO-9001', 'AS9100', 'ITAR'],
    active: true,
  },
  {
    id: 'rapid-proto',
    name: 'Rapid Proto Inc',
    materials: ['al-6061', 'abs-plastic'],
    processes: ['cnc-milling', '3d-print-fdm'],
    maxComplexity: 0.6,
    advancedSurfaces: ['freeform'],
    leadTimeDays: 3,
    qualityRating: 0.78,
    region: 'US-East',
    minOrderUsd: 50,
    pricingMultiplier: 0.9,
    materialPricing: {},
    processPricing: { '3d-print-fdm': 0.85 },
    volumeDiscounts: [
      { minQuantity: 5, discountPct: 3 },
      { minQuantity: 25, discountPct: 8 },
    ],
    certifications: ['ISO-9001'],
    active: true,
  },
  {
    id: 'titan-mfg',
    name: 'Titan Manufacturing',
    materials: ['al-6061', 'al-7075', 'ss-304', 'ss-316', 'ti-6al4v', 'inconel-718'],
    processes: ['cnc-milling', 'cnc-turning', 'edm', 'sheet-metal'],
    maxComplexity: 0.95,
    advancedSurfaces: ['freeform', 'toroidal', 'spherical', 'conical'],
    leadTimeDays: 15,
    qualityRating: 0.98,
    region: 'US-Midwest',
    minOrderUsd: 500,
    pricingMultiplier: 1.3,
    materialPricing: { 'inconel-718': 1.35 },
    processPricing: {},
    volumeDiscounts: [
      { minQuantity: 25, discountPct: 8 },
      { minQuantity: 100, discountPct: 15 },
      { minQuantity: 500, discountPct: 22 },
    ],
    certifications: ['ISO-9001', 'AS9100', 'ITAR', 'NADCAP'],
    active: true,
  },
  {
    id: 'budget-cnc',
    name: 'Budget CNC Co',
    materials: ['al-6061', 'al-7075', 'abs-plastic'],
    processes: ['cnc-milling', 'cnc-turning'],
    maxComplexity: 0.4,
    advancedSurfaces: [],
    leadTimeDays: 8,
    qualityRating: 0.7,
    region: 'Asia-Pacific',
    minOrderUsd: 100,
    pricingMultiplier: 0.7,
    materialPricing: {},
    processPricing: {},
    volumeDiscounts: [
      { minQuantity: 50, discountPct: 10 },
      { minQuantity: 500, discountPct: 20 },
    ],
    certifications: ['ISO-9001'],
    active: true,
  },
  {
    id: 'aero-precision',
    name: 'Aero Precision Group',
    materials: ['ti-6al4v', 'inconel-718', 'ss-316'],
    processes: ['cnc-milling', 'edm'],
    maxComplexity: 0.9,
    advancedSurfaces: ['freeform', 'toroidal', 'spherical'],
    leadTimeDays: 20,
    qualityRating: 0.99,
    region: 'US-East',
    minOrderUsd: 1000,
    pricingMultiplier: 1.45,
    materialPricing: { 'ti-6al4v': 1.1, 'inconel-718': 1.15 },
    processPricing: {},
    volumeDiscounts: [
      { minQuantity: 10, discountPct: 5 },
      { minQuantity: 50, discountPct: 12 },
    ],
    certifications: ['ISO-9001', 'AS9100', 'ITAR', 'NADCAP', 'FAA-PMA'],
    active: true,
  },
];
